<?php
$websiteId = $this->getRequest()->getParam('website_id') ? $this->getRequest()->getParam('website_id') : 0 ;
$helper = Mage::helper('affinityitems/aeadapter');
$helper->registerWebsiteId($websiteId);
$request = new AffinityEngine_AffinityItems_Model_Sdk_Request_SiteRequest(array());
$data = $request->get();
$statistics = Mage::helper('core')->jsonDecode($data['statistics']);
$siteId = $helper->getSiteId();
$categories = $helper->checkSync('categories');
$products = $helper->checkSync('products');
$cart = $helper->checkSync('cart');
$members = $helper->checkSync('members');
$orders = $helper->checkSync('orders');
$actions = $helper->checkSync('actions');
$isSynced = (bool) ($categories && $products && $cart && $orders && $actions);
$initialsync = (count(Mage::getModel('affinityitems/syncrotate')->getCollection())) ? (bool) Mage::getModel('affinityitems/syncrotate')->getCollection()->getFirstItem()->getData('initial_sync') : true;

?>

<div class="aewrapper">
    <?php if ($data['_ok']): ?>
    <div class="items-account">
        <a class="items-manager-button" target="_blank" href="http://manager.affinityitems.com/login/<?php echo $siteId . '/' . $data['authToken']; ?>">
            <div class="items-button">
                <?php echo $this->__('Access my account') ?>
            </div>
        </a>
    </div>
<?php endif; ?>
</div>

<div class="items-wrapper">
    
    
    <?php $websites = Mage::app()->getWebsites(); ?>    
    <p class="switcher"><label for="store_switcher"><?php echo $this->__('Choose website:') ?></label>
    <?php echo $this->getHintHtml() ?>
    <select name="store_switcher" id="store_switcher" class="left-col-block" onchange="return switchStore(this);">
        <!--<option value=""><?php echo $this->__('Please select website') ?></option>-->
        <?php // foreach ($this->getWebsiteCollection() as $_website): ?>
        <?php foreach ($websites as $_website): ?>
                <option website="true" 
                        rel="<?php echo Mage::helper("adminhtml")->getUrl("affinityitems/adminhtml_affinityitemsbackend/index/",array("website_id" => $_website->getId())); ?>"
                        value="<?php echo $_website->getId() ?>"
                        <?php if($websiteId == $_website->getId()): ?> 
                        selected="selected"<?php endif; ?>
                ><?php echo $_website->getName() ?></option>
        <?php endforeach; ?>
    </select>
    </p>
    
    
    <div class="items-header">
        <div class="aelogo"></div>
    </div>
    <div id="items-dashboard" style="display: block;">

        <?php if($data['authToken']) { ?>

        <div class="items-synchronize-container" style="background-color: rgb(130, 200, 54);">

            <div class="items-synchronize-container-text items-left">
                <?php echo $this->__('Affinity items is activated and operational') ?>
            </div>

            <a class="items-manager-button" target="_blank" href="http://manager.affinityitems.com/login/<?php echo $siteId . '/' . $data['authToken']; ?>">
                <div style="color: white;" class="items-synchronize-container-button items-green items-right">
                    <?php echo $this->__('Access my account') ?>
                </div>
            </a>
            <div class="clear"></div>
        </div>

        <?php } else { ?>

        <br />

        <?php } ?>


        <?php // $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); ?>
        <?php $currency_code = Mage::getModel('core/website')->load($websiteId)->getDefaultStore()->getCurrentCurrencyCode(); ?>

        <div class="items-boxes">

            <div class="items-box items-box-black">
                <p><span class="items-box-large-font"><?php echo is_numeric($statistics['onlineUsers']) ? $statistics['onlineUsers'] : 0; ?></span> <br> <span class="items-box-content"> <?php echo $this->__('current'); echo '<br />' . $this->__('connected visitors'); ?> </span></p>
            </div>

            <div class="items-box items-box-black">
                <p><span class="items-box-large-font"><?php echo is_numeric($statistics['cartsInProgress']) ? $statistics['cartsInProgress'] : 0; ?></span> <br> <span class="items-box-content"><?php echo $this->__('current carts'); ?></span></p>
            </div>

            <div class="items-box items-box-purple">
                <p><span class="items-box-large-font"><?php echo is_numeric($statistics['lastMonthVisitsWithRecommendation']) ? $statistics['lastMonthVisitsWithRecommendation'] : 0; ?></span> <br> <span class="items-box-content"><?php echo $this->__('visits'); echo '<br />' . $this->__('with recommendations'); ?></span></p>
            </div>

            <div class="items-box items-box-purple">
                <p><span class="items-box-large-font"><?php echo round(($statistics['bestClickRate']['rate']*100), 2); ?> %</span> <br> <span class="items-box-content"> <?php echo $this->__('recommendations');  echo '<br />' . $this->__('click rate on'); ?> <?php echo $statistics['bestClickRate']['hook'] ?> page*</span></p>
            </div>

            <div class="items-box items-box-purple">
                <p><span class="items-box-large-font"><?php echo round($statistics['lastMonthClickersConversationRate'], 2); ?> %</span> <br> <span class="items-box-content"><?php echo $this->__('transformation'); echo '<br />' . $this->__('rate among clickers'); ?></span></p>
            </div>

            <div class="items-box items-box-black">
                <p><span class="items-box-large-font"><?php echo is_numeric($statistics['lastMonthOrders']) ? $statistics['lastMonthOrders'] : 0;  ?></span> <br> <span class="items-box-content"> <?php echo $this->__('orders'); echo '<br />' . $this->__('during last 30 days'); ?></span></p>
            </div>

            <div class="items-box items-box-black">
                <p><span class="items-box-large-font"><?php echo round($statistics['lastMonthSales'], 0) ?> <?php echo Mage::app()->getLocale()->currency( $currency_code )->getSymbol(); ?></span> <br> <span class="items-box-content"><?php echo $this->__('value sales'); echo '<br />' . $this->__('during last 30 days'); ?> </span></p>
            </div>

            <div class="items-box items-box-purple">
                <p><span class="items-box-large-font"><?php echo is_numeric($data['recommendation']) ? $data['recommendation'] : 0; ?></span> <br> <span class="items-box-content"><?php echo $this->__('recommandations'); echo '<br />' . $this->__('during last 30 days'); ?></span></p>
            </div>

            <div class="items-box items-box-purple">
                <p><span class="items-box-large-font"><?php echo round($statistics['salesAfterClick'], 0) ?> <?php echo Mage::app()->getLocale()->currency( $currency_code )->getSymbol(); ?></span> <br> <span class="items-box-content"><?php echo $this->__('value sales'); echo '<br />' . $this->__('following click on recommendations'); ?></span></p>
            </div>

            <div class="items-box items-box-purple">
                <p><span class="items-box-large-font"><?php echo round($statistics['salesAfterReco'], 0) ?> <?php echo Mage::app()->getLocale()->currency( $currency_code )->getSymbol(); ?></span> <br> <span class="items-box-content"><?php echo $this->__('value sales'); echo '<br />' . $this->__('following a recommendation'); ?></span></p>
            </div>

        </div>

        <div class="clear"></div>
    </div>


    <div class="items-synchronization">
        <div>
            <?php if ($initialsync):?>
            <h2><?php echo $this->__('Initial sync in progress'); ?></h2>
        <?php else:?>
        <h2><?php echo ($isSynced) ? $this->__('Your system is synchronized') : $this->__('Your system is not synchronized'); ?></h2>
    <?php endif;?>
</div>
<div>
    <ul>
        <li class="<?php echo ($categories) ? 'aechecked' : 'aeunchecked'; ?>"><?php echo $this->__('Categories synchronization'); ?></li>
        <li class="<?php echo ($products) ? 'aechecked' : 'aeunchecked'; ?>"><?php echo $this->__('Products synchronization'); ?></li>
        <li class="<?php echo ($members) ? 'aechecked' : 'aeunchecked'; ?>"><?php echo $this->__('Members synchronization'); ?></li>
        <li class="<?php echo ($orders) ? 'aechecked' : 'aeunchecked'; ?>"><?php echo $this->__('Orders synchronization'); ?></li>
        <li class="<?php echo ($cart) ? 'aechecked' : 'aeunchecked'; ?>"><?php echo $this->__('Carts synchronization'); ?></li>
        <li class="<?php echo ($actions) ? 'aechecked' : 'aeunchecked'; ?>"><?php echo $this->__('Actions synchronization'); ?></li>
    </ul>
</div>
</div>

</div>

<script type="text/javascript">
    function switchStore(obj){
        var redirecrUrl = obj.options[obj.selectedIndex].getAttribute('rel');
        setLocation(redirecrUrl);
    }
</script>