<?php $helper = $this->helper('affinityitems'); ?>
<?php $blockName = $this->getNameInLayout(); ?>
<?php if ($blockName == 'ae_vertical_right'): ?>
    <?php $enable_column = $helper->isRightEnabled(); ?>
    <?php $imagesize = $helper->getRImageSize(); ?>
    <?php $css = "right";?>
<?php elseif ($blockName == 'ae_vertical_left'): ?>
    <?php $enable_column = $helper->isLeftEnabled(); ?>
    <?php $imagesize = $helper->getLImageSize(); ?>
    <?php $css = "left";?>
<?php else: ?>
    <?php $enable_column = false; ?>
<?php endif; ?>

<?php if ($enable_column ): ?>
    <?php $productCollection = $this->getProductCollection($blockName); ?>
    <?php if ($productCollection && count($productCollection)): ?>
        <div class="ae-area ae-<?php echo $css;?>">
            <div id="<?php echo $helper->getId('parent_div'); ?>" class="<?php echo $helper->getClass('parent_div'); ?>">
                <h4 class="<?php echo $helper->getClass('title_class'); ?>"><?php echo $helper->getSideTitle($this->getNameInLayout()); ?></h4>
                <div id="<?php echo $helper->getId('content_div'); ?>" class="<?php echo $helper->getClass('content_div'); ?>">
                    <ul id="<?php echo $helper->getId('ul'); ?>" class="<?php echo $helper->getClass('ul'); ?>">
                        <?php $i=0 ?>
                        <?php foreach ($productCollection as $product): ?>
                            <?php if (Mage::registry('current_product') && Mage::registry('current_product')->getId() == $product->getId()) continue; ?>
                            <?php $product = Mage::getModel('catalog/product')->load($product->getId()); ?>
                            <?php if ($helper->canDisplayProduct($product)) continue;?>
                            <?php $pname = $this->escapeHtml($product->getName()); ?>
                            <li id="<?php echo $helper->getId('li'); ?>" class="<?php echo $helper->getClass('li'); ?> <?php if(($i % $helper->getConfig('number_products_per_line')) == ($helper->getConfig('number_products_per_line') - 1)) echo 'ae_last_item_of_line'; ?>">
                                <a rel="<?php echo $product->getId()?>" href="<?php echo $helper->getFullProductUrl($product); ?>" title="<?php echo $pname ?>" rel="<?php echo $product->getId() ?>"><img class="<?php echo $helper->getClass('product_image_class'); ?>" src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize($imagesize[0], $imagesize[1]) ?>"" height="<?php echo $imagesize[0]; ?>" width="<?php echo $imagesize[1]; ?>" alt="<?php echo $pname ?>" /></a>
                                <h5 itemprop="name">
                                    <a rel="<?php echo $product->getId()?>" class="<?php echo $helper->getClass('product_name_class'); ?>" href="<?php echo $helper->getFullProductUrl($product); ?>"  rel="<?php echo $pname ?>" title="<?php echo $pname ?>"><?php echo $pname ?></a>
                                </h5>					
                                <div>
                                    <p class="<?php echo $helper->getClass('product_description_class'); ?>"><?php echo Mage::helper('core/string')->truncate($product->getShortDescription(), 40); ?></p>
                                    <p class="<?php echo $helper->getClass('price_container_class'); ?>"><span class="<?php echo $helper->getClass('price_class'); ?>"><?php echo $helper->getFormatedPrice($product); ?></span></p>
                                </div>
                            </li>
                            <?php $i++; ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
